### ISSUE TITLE
Sitemap - Blueberries

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/plan-a-website#1]
[blueberries-sitemap.pdf](https://github.com/C-G-G/plan-a-website/files/5976510/blueberries-sitemap.pdf)

@thomasjbradley

Unfortunately not a registered student here so please ignore if you don't have time to review.

**Comment by thomasjbradley** [comment]
You can probably combine “About” & “Home” together because there are only 3 navigation items.

I’d also likely name the item “Berries” instead of “Types” to be more descriptive.
